text text **text**

In [9]:
import numpy as np

a = np.array([[1, 2, 3], 
              [3, 4, 5], 
              [4, 6, 8]])
n = 7
b = np.random.rand(n, n)
x = np.random.rand(n)
y = b @ (x)
c = np.linalg.inv(b)
v = c @ y
print(v - x)

[ -9.99200722e-16   2.44249065e-15   3.33066907e-16   0.00000000e+00
  -6.66133815e-16   1.99840144e-15  -4.44089210e-16]


In [13]:
import numpy as np

def generate(n):
    def create(matrix):
        if np.linalg.det(matrix) != 0:
            return matrix
        else:
            return create(np.random.rand(n, n))
    return create(np.random.rand(n, n))



[[ 0.90599314  0.89034534  0.44049817  0.17976116  0.25345246]
 [ 0.92483662  0.48476236  0.66830024  0.8869607   0.4483664 ]
 [ 0.69083159  0.55307319  0.96758505  0.85054676  0.03320607]
 [ 0.1304701   0.54155365  0.81654472  0.68291136  0.0066158 ]
 [ 0.76456612  0.97733968  0.84484224  0.71892641  0.09452552]]


In [22]:
# generate a nice invertible A in one line (and x in one line, y in one line)
# given y and A in y = Ax, return x
# bonus points:
# * given a true value of x, check to make sure your estimation is close to the true x
# * check how you state how close it is
# * when you check, use a NumPy function

# generate n x n matrices that are not invertible
# do this by 2 ways as judged different by Scott
# write a (not very general) method for this

import numpy as np

def generate_linear_system(n):
    # Benefits of nested functions: They allow abstractions within abstractions, reduce global 
    # scope clutter for actions only relevant to the function, and conveniently package the 
    # function so it has no global-scope dependencies and therefore make the function, in some 
    # sense, more "pure."
    def create(matrix): # need function to make sure created system is invertable, if singular, 
                        # then make a new one and check to make sure not singular
        if np.linalg.det(matrix) != 0:
            return matrix
        else: # else for clarity and uniformity
            return create(np.random.rand(n, n))
    A = create(np.random.rand(n, n))
    x = np.random.rand(n)
    y = A @ x
    return {"A": A, "x": x, "y": y}
def x(system):
    A, y = system["A"], system["y"]
    try:
        alpha = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        raise
    else:
        return alpha @ y
    return False
def is_close(x1, x2):
    return np.allclose(x1, x2)
def not_inv_col(n):
    row_scales = np.random.rand(n)
    row_scales[np.random.randint(0, n)] = 0
    return np.array([[scale * elt for elt in np.random.rand(n)] for scale in row_scales])
# def notInvRow(n):
#     rowScales = np.random.rand(n)
#     rowScales[np.random.randint(0, n)] = 0
#     return np.matrix([[scale * elt for elt in np.random.rand(n)] for scale in rowScales])
def not_inv_sum(n):
    def translate_matrix(matrix):
        return [[matrix[row][column] for row in range(len(matrix))] for column in range(len(matrix))]
    def reduce_matrix_rows(matrix):
        return [sum(matrix[column]) for column in range(len(matrix))]
    matrix = np.random.rand(n - 1, n)
    np.insert(matrix, np.random.randint(0, n), reduce_matrix_rows(translate_matrix(matrix)))
    return np.array(matrix)
# sys = generateSystem(10)
# sysX = x(sys)
# print(isClose(sysX, sys["x"]))
# print(sysX, sys["x"])
# i = not_inv_sum(3)
#print(i, np.linalg.inv(i))
# print(i)
q = generate_linear_system(5)["A"]
print(np.linalg.inv(q) @ q)

[[  1.00000000e+00  -1.11022302e-16  -5.55111512e-17   5.55111512e-17
    0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00  -3.33066907e-16  -3.88578059e-16
   -2.22044605e-16]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -3.88578059e-16
    0.00000000e+00]
 [  0.00000000e+00   2.22044605e-16   1.11022302e-16   1.00000000e+00
    4.44089210e-16]
 [  1.66533454e-16   5.55111512e-17   0.00000000e+00   2.77555756e-17
    1.00000000e+00]]


In [45]:
# generate a nice invertible A in one line (and x in one line, y in one line)
# given y and A in y = Ax, return x
# bonus points:
# * given a true value of x, check to make sure your estimation is close to the true x
# * check how you state how close it is
# * when you check, use a NumPy function

# generate n x n matrices that are not invertible
# do this by 2 ways as judged different by Scott
# write a (not very general) method for this

import numpy as np

def generate_linear_system(n):
    # Benefits of nested functions: They allow abstractions within abstractions, reduce global 
    # scope clutter for actions only relevant to the function, and conveniently package the 
    # function so it has no global-scope dependencies and therefore make the function, in some 
    # sense, more "pure."
    def create(matrix): # need function to make sure created system is invertable, if singular, 
                        # then make a new one and check to make sure not singular
        if np.linalg.det(matrix) != 0:
            return matrix
        else: # else for clarity and uniformity
            return create(np.random.rand(n, n))
    A = create(np.random.rand(n, n))
    x = np.random.rand(n)
    y = A @ x
    return {"A": A, "x": x, "y": y}
def x(system):
    A, y = system["A"], system["y"]
    try:
        alpha = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        raise
    else:
        return alpha @ y
    return False
def is_close(x1, x2):
    return np.allclose(x1, x2)
# translate_matrix has shared functionality valaid to other parts of program so is in global scope and 
# other matrix operations valid as stand-alone abstractions
def translate_matrix(matrix):
    row_length, column_length = len(matrix), len(matrix[0])
    return [[matrix[row][column] for row in range(len(matrix))] for column in range(len(matrix[0]))]
# def reverse_translate_matrix(matrix):
#    row_length, column_length = len(matrix), len(matrix[0])
#    return [[matrix[row_length - row - 1][column] for row in range(row_length)] for column in range(column_length)]
def reduce_matrix_rows(matrix):
    return [sum(matrix[column]) for column in range(len(matrix))]
def scale_columns(matrix, scales): # assumes length of scales (list) is same as length of a row in matrix
    translated = translate_matrix(matrix)
    scaled = [[scales[i] * elt for elt in translated[i]] for i in range(len(translated))]
    return translate_matrix(scaled)
def not_inv_row(n):
    row_scales = np.random.rand(n)
    row_scales[np.random.randint(0, n)] = 0
    # scales rows individually to different scales
    return np.array([[scale * elt for elt in np.random.rand(n)] for scale in row_scales])
def not_inv_column(n):
    column_scales = np.random.rand(n)
    column_scales[np.random.randint(0, n)] = 0
    return scale_columns(np.random.rand(n, n), column_scales)
# def notInvRow(n):
#     rowScales = np.random.rand(n)
#     rowScales[np.random.randint(0, n)] = 0
#     return np.matrix([[scale * elt for elt in np.random.rand(n)] for scale in rowScales])
def not_inv_sum(n):
    matrix = np.random.rand(n - 1, n)
    np.insert(matrix, np.random.randint(0, n), reduce_matrix_rows(translate_matrix(matrix)))
    return np.array(matrix)
# sys = generateSystem(10)
# sysX = x(sys)
# print(isClose(sysX, sys["x"]))
# print(sysX, sys["x"])
#i = not_inv_sum(3)
#print(i, np.linalg.inv(i))
scale_columns([[1,2,3],[4,5,6],[7,8,9]], [1,0,2])
print(not_inv_column(5))
print(not_inv_row(5))
# print(i)
# q = generate_linear_system(5)["A"]
# print(np.linalg.inv(q) @ q)

[[0.0, 0.20675089431843965, 0.14730009326926446, 0.011435018526470917, 0.59479229699586045], [0.0, 0.52936475200966293, 0.48458197617920251, 0.043260546530910209, 0.028514799689732105], [0.0, 0.27688831953073001, 0.3842373518899817, 0.00507356328142406, 0.23829745276865624], [0.0, 0.091454028186211817, 0.52815064833900849, 0.036988606115941618, 0.4654193486478132], [0.0, 0.35703534937579035, 0.10751005603848988, 0.037468673456539391, 0.079114994605273214]]


LinAlgError: Singular matrix

In [ ]:
import numpy as np

def generate_linear_system(n):
    # Benefits of nested functions: They allow abstractions within abstractions, reduce global 
    # scope clutter for actions only relevant to the function, and conveniently package the 
    # function so it has no global-scope dependencies and therefore make the function, in some 
    # sense, more "pure."
    def create(matrix): # need function to make sure created system is invertable, if singular, 
                        # then make a new one and check to make sure not singular
        if np.linalg.det(matrix) != 0:
            return matrix
        else: # else for clarity and uniformity
            return create(np.random.rand(n, n))
    A = create(np.random.rand(n, n))
    x = np.random.rand(n)
    y = A @ x
    return {"A": A, "x": x, "y": y}
def x(system):
    A, y = system["A"], system["y"]
    try:
        alpha = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        raise
    else:
        return alpha @ y
    return False
def is_close(x1, x2):
    return np.allclose(x1, x2)

# translate_matrix has shared functionality valaid to other parts of program so is in global scope and 
# other matrix operations valid as stand-alone abstractions, too
def translate_matrix(matrix):
    row_length, column_length = len(matrix), len(matrix[0])
    return [[matrix[row][column] for row in range(len(matrix))] for column in range(len(matrix[0]))]
def reduce_matrix_rows(matrix):
    return [sum(matrix[column]) for column in range(len(matrix))]
def scale_columns(matrix, scales): # assumes length of scales (list) is same as length of a row in matrix
    translated = translate_matrix(matrix)
    scaled = [scalar_mult(translated[i], scales[i]) for i in range(len(translated))]
    return translate_matrix(scaled)
def scalar_mult(row, scale):
    return [scale * elt for elt in row]

def not_inv_row(n):
    row_scales = np.random.rand(n)
    row_scales[np.random.randint(0, n)] = 0
    # scales rows individually to different scales
    return np.array([scalar_mult(np.random.rand(n), scale) for scale in row_scales])
def not_inv_column(n):
    column_scales = np.random.rand(n)
    column_scales[np.random.randint(0, n)] = 0
    return scale_columns(np.random.rand(n, n), column_scales)
def not_inv_sum(n):
    matrix = np.random.rand(n - 1, n)
    np.insert(matrix, np.random.randint(0, n), reduce_matrix_rows(translate_matrix(matrix)))
    return np.array(matrix)