text text **text**

In [9]:
import numpy as np

a = np.array([[1, 2, 3], 
              [3, 4, 5], 
              [4, 6, 8]])
n = 7
b = np.random.rand(n, n)
x = np.random.rand(n)
y = b @ (x)
c = np.linalg.inv(b)
v = c @ y
print(v - x)

[ -9.99200722e-16   2.44249065e-15   3.33066907e-16   0.00000000e+00
  -6.66133815e-16   1.99840144e-15  -4.44089210e-16]


In [13]:
import numpy as np

def generate(n):
    def create(matrix):
        if np.linalg.det(matrix) != 0:
            return matrix
        else:
            return create(np.random.rand(n, n))
    return create(np.random.rand(n, n))



[[ 0.90599314  0.89034534  0.44049817  0.17976116  0.25345246]
 [ 0.92483662  0.48476236  0.66830024  0.8869607   0.4483664 ]
 [ 0.69083159  0.55307319  0.96758505  0.85054676  0.03320607]
 [ 0.1304701   0.54155365  0.81654472  0.68291136  0.0066158 ]
 [ 0.76456612  0.97733968  0.84484224  0.71892641  0.09452552]]


In [51]:
# generate a nice invertible A in one line (and x in one line, y in one line)
# given y and A in y = Ax, return x
# bonus points:
# * given a true value of x, check to make sure your estimation is close to the true x
# * check how you state how close it is
# * when you check, use a NumPy function

# generate n x n matrices that are not invertible
# do this by 2 ways as judged different by Scott
# write a (not very general) method for this

import numpy as np

def generateSystem(n):
    def create(matrix):
        if np.linalg.det(matrix) != 0:
            return matrix
        else:
            return create(np.random.rand(n, n))
    A = create(np.random.rand(n, n))
    x = np.random.rand(n)
    y = A @ x
    return {"A": A, "x": x, "y": y}
def x(system):
    A = system["A"]
    y = system["y"]
    try:
        alpha = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        raise
    else:
        return alpha @ y
    return False
def isClose(x1, x2):
    return np.allclose(x1, x2)
def notInvCol(n):
    rowScales = np.random.rand(n)
    rowScales[np.random.randint(0, n)] = 0
    return np.array([[scale * elt for elt in np.random.rand(n)] for scale in rowScales])
# def notInvRow(n):
#     rowScales = np.random.rand(n)
#     rowScales[np.random.randint(0, n)] = 0
#     return np.matrix([[scale * elt for elt in np.random.rand(n)] for scale in rowScales])
def notInvSum(n):
    matrix = []
    i = n - 1
    while i > 0:
        matrix.append([int(np.floor(elt * 10)) for elt in np.random.rand(n)])
        i -= 1
    row = [[matrix[row][column] for row in range(n - 1)] for column in range(n)]
    row = [sum(row[column]) for column in range(n)]
    matrix.insert(np.random.randint(0, n), row)
    return np.array(matrix)
    
# sys = generateSystem(10)
# sysX = x(sys)
# print(isClose(sysX, sys["x"]))
# print(sysX, sys["x"])
i = notInvSum(3)
print(i, np.linalg.inv(i))
# print(i)
# q = generateSystem(5)["A"]
# print(np.linalg.inv(q) @ q)

LinAlgError: Singular matrix